services:
  app:
    depends_on:
      - mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT_FORWARD}:${APP_PORT}"
    volumes:
      - ./:/opt/apps/app
      - mvn_deps:/opt/apps/maven/repository
      - target_data:/opt/apps/app/target
    env_file:
      - .env
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - app
      - accessible
    labels:
      - traefik.enable=true
      - traefik.http.routers.games.rule=Host(`games.henrotaym.ip-ddns.com`)
      - traefik.http.routers.games.tls=true
    restart: unless-stopped

  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${DB_PORT_FORWARD}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_ROOT}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE_TEST: "${DB_DATABASE_TEST}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./devops/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app
    restart: unless-stopped


networks:
  app:
    driver: bridge
  accessible:
    external: true

volumes:
  mysql_data:
    driver: local
  mvn_deps:
    driver: local
  target_data:
    driver: local
  redis_data:
    driver: local
